// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/edwardkerckhof/goblog/internal/core/services/post"
	"github.com/edwardkerckhof/goblog/internal/handlers/post"
	"github.com/edwardkerckhof/goblog/internal/repositories/post"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func SetupPostHandler(db *gorm.DB) post_handler.PostHandler {
	postRepository := post_repository.NewGormRepository(db)
	postService := post_service.NewPostService(postRepository)
	postHandler := post_handler.NewHTTPHandler(postService)
	return postHandler
}
